project:
  type: website
  output-dir: docs

website:
  title: "Home"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: twitter
        href: https://x.com/m_shahoyi
      - icon: linkedin
        href: https://www.linkedin.com/in/mohammedshahoe/
      - icon: github
        href: https://github.com/mshahoyi

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
