project:
  type: website
  output-dir: docs
  resources:
    - assets/cv.pdf

website:
  title: "Home"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: "CV"
        href: assets/cv.pdf # relative URL
        target: _blank # open in a new tab (optional)
      - icon: twitter
        href: https://x.com/m_shahoyi
      - icon: linkedin
        href: https://www.linkedin.com/in/mohammedshahoe/
      - icon: github
        href: https://github.com/mshahoyi

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
